In [72]:
from multiprocessing.sharedctypes import Value
from select import select
from tkinter.tix import Select
from turtle import goto
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
import time, json
from webdriver_manager.firefox import GeckoDriverManager
import os
import sys
from selenium.webdriver.common.by import By
import pandas as pd
from tkinter import messagebox
from selenium.webdriver.common.alert import Alert 
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains
import numpy as np
import re 





os.path.dirname(sys.executable)

from time import sleep, strftime 
from selenium import webdriver
# esto se prueba en Firefox o puede usar el navegador "webdriver.Chrome()" 
browser = webdriver.Firefox(executable_path=r'C:\Users\yazie\OneDrive\Documentos\PYTHON\Altas-Empleados\geckodriver.exe')
browser.get('http://www.eraindefleet.com/TPB')
df=pd.read_excel(r'C:\Users\yazie\Downloads\Evidencia_ECM.xlsx',engine='openpyxl',sheet_name=0,header=0)
dt=pd.read_excel(r'C:\Users\yazie\Downloads\nombre archivos.xlsx',engine='openpyxl',sheet_name=0,header=0)
db=pd.read_excel(r'C:\Users\yazie\Downloads\bitacoras.xlsx',engine='openpyxl',sheet_name=0,header=0)
#DATOS LOG IN
user= 'YBARBOSA'
psw= 'Ybarbosa_22'
timeout=120


usuario= browser.find_element(By.XPATH, '//*[@id="usuario"]')
usuario.send_keys(user)
contrase√±a= browser.find_element(By.XPATH,'//*[@id="contrasena"]')
contrase√±a.send_keys(psw)
click_login= browser.find_element(By.XPATH,'//*[@id="Button1"]')
click_login.click()

#Entramos a men√∫ WebDriverWait(browser, timeout).until(EC.element_to_be_clickable((By.XPATH,'/html/body/form/div[5]/div/ul/li[9]/a')))
button_mesacontrol=WebDriverWait(browser, timeout).until(EC.element_to_be_clickable((By.XPATH,'/html/body/form/div[5]/div/ul/li[9]/a')))
#button_mesacontrol= browser.find_element(By.XPATH,'/html/body/form/div[5]/div/ul/li[9]/a')
button_mesacontrol.click()
sleep(3)

#click Boton Facturar
button_report=browser.find_element(By.XPATH,'/html/body/form/div[6]/div/div[2]/ul[2]/li/a')
button_report.click()
sleep(3)
main_page = browser.current_window_handle 
principal=main_page
#erre=[]
#b=[]
#erre=list(np.arange(1,10000+1))
#b=list(range(1,11+1))

#dt=pd.DataFrame(a,b) #DataFrame constructor not properly called!

#lIBRO ESTADISTICA APLICADA : 318-319
for j in range(len(df)):
    print(j+1)
    print(df.iloc[j,0])
    fecha_1=df.iloc[j,0]
    fecha_2=df.iloc[j,1]
    bitacora=df.iloc[j,2]
    print(bitacora)
    print(len(bitacora))

    fecha_1_key=WebDriverWait(browser, timeout).until(EC.visibility_of_element_located((By.XPATH,'//*[@id="txtFechaIn"]')))
    fecha_1=fecha_1.strftime('%d/%m/%Y')
    fecha_1_key.clear()
    fecha_1_key.send_keys(fecha_1)    

    fecha_2_key=WebDriverWait(browser, timeout).until(EC.visibility_of_element_located((By.XPATH,'//*[@id="txtFechaFin"]')))
    fecha_2=fecha_2.strftime('%d/%m/%Y')
    fecha_2_key.clear()
    fecha_2_key.send_keys(fecha_2)

    button_liqui=WebDriverWait(browser, timeout).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="rbrLiquidacion_2"]'))) 
    button_liqui.click()

    
    bitacora_key=WebDriverWait(browser, timeout).until(EC.visibility_of_element_located((By.XPATH,'//*[@id="FBitacora"]')))
    bitacora=str(bitacora)
    bitacora_key.send_keys(bitacora)

    #No se actualiza con un click
    button_search=WebDriverWait(browser, timeout).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="btnBuscar"]'))) 
    button_search.click()
    button_search=WebDriverWait(browser, timeout).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="btnBuscar"]'))) 
    button_search.click()

    #//*[@id="A1"]
    #//*[@id="A1"]
    evidencias=WebDriverWait(browser, timeout).until(EC.presence_of_all_elements_located((By.XPATH,'//*[@id="A1"]'))) 
    print(len(evidencias))
    df.iloc[j,4]=len(evidencias)
    
    m=0
    documents=[]
    bitacoras_=[]
    if len(evidencias)>1:
        #for s in browser.find_elements_by_xpath('//*[@id="A1"]'):
            #print(s)
        value_2 = browser.find_element_by_xpath('//*[@id="GridViewBitacora"]').text
        lista=value_2.split(" ")
        print(lista) 
        for i in range(len(lista)):
            a=lista[i]
            #print(a)
            #if len(a)==9:
            #    m = re.findall('[0-9]+',a)
            #    if len(m)==6:
            #        print(a)
            #        bitacoras.append(a)
            
            r=a.find('.pdf')
            #print(r)
            if r!=-1:
                bitacoras_.append(bitacora)
                documents.append(a)
                #print(r)
                #print(len(a))
                print(a + " a")
                #print(type(a))
                #b=str(a)
                #print(len(b))
                #print(b + " b")
                
                
    #        s.click()
    #        sleep(3)
    else:
        f=browser.find_element_by_xpath('//*[@id="A1"]')
    #    f.click()
        value_2 = browser.find_element_by_xpath('//*[@id="GridViewBitacora"]').text
        #print(value_2)
        lista=value_2.split(" ")
        #print(lista)
        
        for i in range(len(lista)):
            a=lista[i]

            #if len(a)==9:
            #    m = re.findall('[0-9]+',a)
            #    if len(m)==6:
            #        print(a)
            #        bitacoras.append(a)

            r=a.find('.pdf')
            #print(r)
            if r!=-1:
                bitacoras_.append(bitacora)
                documents.append(a)
                #print(r)
                #print(len(a))
                print(a + " a")
                #print(type(a))
                #b=str(a)
                #print(len(b))
                #print(b + " b")
                #dt.loc[j,i]=str(b) #Verificar si el df 

        #for i in range(len(lista)):
        #    a=lista[i]
            #print(a)
        #    r=a.find('.pdf')
            #print(r)
        #    if r!=-1:
        #        print(len(a))
        #        print(a + " a")
        #        b=str(b)
        #        print(len(b))
        #        print(b + " b")
                #dt.iloc[j,i]=str(b)

    
    
    #print(evidencias)
    #print(len(evidencias))
    #num_ev=len(evidencias)
    #if num_ev>1:
    #    for s in range(0,len(evidencias)):
    #        button_ev=browser.find_element_by


    #Clear
    dt=dt.append(documents,ignore_index=True)
    db=db.append(bitacoras_,ignore_index=True)
    print(db)
    bitacora_key=browser.find_element(By.XPATH,'//*[@id="FBitacora"]')
    bitacora_key.clear()
    sleep(3)
    #fecha_1_key=browser.find_element(By.XPATH,'//*[@id="txtFechaIn"]')
    #fecha_1_key.clear()
    #sleep(3)
    #fecha_2_key=browser.find_element(By.XPATH,'//*[@id="txtFechaFin"]')
    #fecha_2_key.clear()
    #tipo.send_keys(Keys.CLEAR)
    #factura.send_keys(Keys.CLEAR)
    #sleep(3)



df.to_excel(r'C:\Users\yazie\a_5.xlsx')
dt.to_excel(r'C:\Users\yazie\b_5.xlsx')
db.to_excel(r'C:\Users\yazie\c_5.xlsx')

1
2022-05-31 00:00:00
MTY115984
9
4
['', '', 'Documentos', 'Con', 'Documentos\n\nBase\n\nBitacora\n\nUnidad', 'Tipo', 'Documento', 'Lig.', '', '', 'Salida', 'Llegada', 'Programada\n\nOperador', 'Origen', 'Destino', '(Cargado)', 'Destino', '(Retorno)', 'MOV.', 'CORREDOR', 'VINES', 'Nombre', 'Archivo', 'Tipo', 'Archivo', 'Observaciones', 'Con', 'Da√±o\n1', '', 'SI', 'MTY', 'MTY115984', 'TRF-016', 'CP', '43392', '', '', '28/05/2022', '21:17', '29/05/2022', '20:14', 'GUZMAN', 'HERNANDEZ', 'FRANCISCO', 'DERRAMADERO', 'ALTAMIRA', 'ALTAMIRA', '0', 'doc07975220220530083805.pdf', 'application/pdf', '', '\n2', '', 'SI', 'MTY', 'MTY115984', 'TRF-016', 'CP', '43392', '', '', '28/05/2022', '21:17', '29/05/2022', '20:14', 'GUZMAN', 'HERNANDEZ', 'FRANCISCO', 'DERRAMADERO', 'ALTAMIRA', 'ALTAMIRA', '0', 'doc07985720220530204445.pdf', 'application/pdf', '', '\n3', '', 'SI', 'MTY', 'MTY115984', 'TRF-016', 'CP', '43392', '', '', '28/05/2022', '21:17', '29/05/2022', '20:14', 'GUZMAN', 'HERNANDEZ', 'FRANCISCO', 'DERRAMADERO', 'ALTAMIRA', 'ALTAMIRA', '0', 'doc07985820220530204514.pdf', 'application/pdf', '', '\n4', '', 'SI', 'MTY', 'MTY115984', 'TRF-016', 'CP', '43392', '', '', '28/05/2022', '21:17', '29/05/2022', '20:14', 'GUZMAN', 'HERNANDEZ', 'FRANCISCO', 'DERRAMADERO', 'ALTAMIRA', 'ALTAMIRA', '0', 'doc07991620220531094259.pdf', 'application/pdf', '', '']
doc07975220220530083805.pdf a
doc07985720220530204445.pdf a
doc07985820220530204514.pdf a
doc07991620220531094259.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
2
2022-05-31 00:00:00
MZO115867
9
1
TR-378.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
3
2022-05-31 00:00:00
MZO115858
9
1
353.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
4
2022-05-31 00:00:00
MZO115863
9
1
011.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
5
2022-05-31 00:00:00
MZO115576
9
1
026.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7  MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
6
2022-05-31 00:00:00
MTY115870
9
1
026.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7  MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8  MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
7
2022-05-31 00:00:00
ALT115767
9
1
256.pdf a
           0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7  MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8  MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9  ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

  elemento
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
8
2022-05-31 00:00:00
MTY115855
9
1
tr-286.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
9
2022-05-31 00:00:00
ALT116009
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
10
2022-05-31 00:00:00
MTY115934
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
11
2022-05-31 00:00:00
MTY115974
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
13  NaN      NaN
12
2022-05-31 00:00:00
MZO115783
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  MZO115783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
13  NaN      NaN
14  NaN      NaN
13
2022-05-31 00:00:00
MZO115985
9
1
345.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  MZO115783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  MZO115985  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
13  NaN      NaN
14  NaN      NaN
15  NaN      NaN
14
2022-05-31 00:00:00
ALT116074
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  MZO115783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  MZO115985  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  ALT116074  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
13  NaN      NaN
14  NaN      NaN
15  NaN      NaN
16  NaN      NaN
15
2022-05-31 00:00:00
MTY115977
9
1
DESCARGA.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  MZO115783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  MZO115985  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  ALT116074  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17  MTY115977  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

     13 elemento
0   NaN      NaN
1   NaN      NaN
2   NaN      NaN
3   NaN      NaN
4   NaN      NaN
5   NaN      NaN
6   NaN      NaN
7   NaN      NaN
8   NaN      NaN
9   NaN      NaN
10  NaN      NaN
11  NaN      NaN
12  NaN      NaN
13  NaN      NaN
14  NaN      NaN
15  NaN      NaN
16  NaN      NaN
17  NaN      NaN
16
2022-06-01 00:00:00
MTY116017
9
1
029.pdf a
            0    1    2    3    4    5    6    7    8    9   10   11   12  \
0   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   MTY115984  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   MZO115867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   MZO115858  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   MZO115863  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7   MZO115576  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8   MTY115870  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9   ALT115767  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  MTY115855  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11  ALT116009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12  MTY115934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13  MTY115974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
14  MZO115783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  MZO115985  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  ALT116074  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17  MTY115977  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN